<?xml version="1.0" encoding="utf-8"?><Database Name="Epicor10Production" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=ITSQL;Initial Catalog=Epicor10Production;Integrated Security=True" SettingsObjectName="SalesOrdEntry.Properties.Settings" SettingsPropertyName="Epicor10ProductionConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="Erp.Part" Member="Parts">
    <Type Name="Part">
      <Column Name="Company" Type="System.String" DbType="NVarChar(8) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="PartNum" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="SearchWord" Type="System.String" DbType="NVarChar(8) NOT NULL" CanBeNull="false" />
      <Column Name="PartDescription" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="ClassID" Type="System.String" DbType="NVarChar(4) NOT NULL" CanBeNull="false" />
      <Column Name="IUM" Type="System.String" DbType="NVarChar(6) NOT NULL" CanBeNull="false" />
      <Column Name="PUM" Type="System.String" DbType="NVarChar(6) NOT NULL" CanBeNull="false" />
      <Column Name="TypeCode" Type="System.String" DbType="NVarChar(2) NOT NULL" CanBeNull="false" />
      <Column Name="NonStock" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="PurchasingFactor" Type="System.Decimal" DbType="Decimal(14,4) NOT NULL" CanBeNull="false" />
      <Column Name="UnitPrice" Type="System.Decimal" DbType="Decimal(17,5) NOT NULL" CanBeNull="false" />
      <Column Name="PricePerCode" Type="System.String" DbType="NVarChar(2) NOT NULL" CanBeNull="false" />
      <Column Name="InternalUnitPrice" Type="System.Decimal" DbType="Decimal(17,5) NOT NULL" CanBeNull="false" />
      <Column Name="InternalPricePerCode" Type="System.String" DbType="NVarChar(2) NOT NULL" CanBeNull="false" />
      <Column Name="ProdCode" Type="System.String" DbType="NVarChar(8) NOT NULL" CanBeNull="false" />
      <Column Name="MfgComment" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="PurComment" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="CostMethod" Type="System.String" DbType="NVarChar(2) NOT NULL" CanBeNull="false" />
      <Column Name="UserChar1" Type="System.String" DbType="NVarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="UserChar2" Type="System.String" DbType="NVarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="UserChar3" Type="System.String" DbType="NVarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="UserChar4" Type="System.String" DbType="NVarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="UserDate1" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="UserDate2" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="UserDate3" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="UserDate4" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="UserDecimal1" Type="System.Decimal" DbType="Decimal(12,2) NOT NULL" CanBeNull="false" />
      <Column Name="UserDecimal2" Type="System.Decimal" DbType="Decimal(12,2) NOT NULL" CanBeNull="false" />
      <Column Name="UserDecimal3" Type="System.Decimal" DbType="Decimal(15,5) NOT NULL" CanBeNull="false" />
      <Column Name="UserDecimal4" Type="System.Decimal" DbType="Decimal(15,5) NOT NULL" CanBeNull="false" />
      <Column Name="UserInteger1" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="UserInteger2" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TaxCatID" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="InActive" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="LowLevelCode" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Method" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="TrackLots" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="TrackDimension" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="DefaultDim" Type="System.String" DbType="NVarChar(6) NOT NULL" CanBeNull="false" />
      <Column Name="TrackSerialNum" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="CommodityCode" Type="System.String" DbType="NVarChar(12) NOT NULL" CanBeNull="false" />
      <Column Name="WarrantyCode" Type="System.String" DbType="NVarChar(8) NOT NULL" CanBeNull="false" />
      <Column Name="PhantomBOM" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="SalesUM" Type="System.String" DbType="NVarChar(6) NOT NULL" CanBeNull="false" />
      <Column Name="SellingFactor" Type="System.Decimal" DbType="Decimal(18,8) NOT NULL" CanBeNull="false" />
      <Column Name="MtlBurRate" Type="System.Decimal" DbType="Decimal(7,2) NOT NULL" CanBeNull="false" />
      <Column Name="NetWeight" Type="System.Decimal" DbType="Decimal(15,5) NOT NULL" CanBeNull="false" />
      <Column Name="UsePartRev" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="PartsPerContainer" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PartLength" Type="System.Decimal" DbType="Decimal(15,5) NOT NULL" CanBeNull="false" />
      <Column Name="PartWidth" Type="System.Decimal" DbType="Decimal(15,5) NOT NULL" CanBeNull="false" />
      <Column Name="PartHeight" Type="System.Decimal" DbType="Decimal(15,5) NOT NULL" CanBeNull="false" />
      <Column Name="LotShelfLife" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="WebPart" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="RunOut" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="SubPart" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Diameter" Type="System.Decimal" DbType="Decimal(15,5) NOT NULL" CanBeNull="false" />
      <Column Name="Gravity" Type="System.Decimal" DbType="Decimal(15,5) NOT NULL" CanBeNull="false" />
      <Column Name="OnHold" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="OnHoldDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="OnHoldReasonCode" Type="System.String" DbType="NVarChar(8) NOT NULL" CanBeNull="false" />
      <Column Name="AnalysisCode" Type="System.String" DbType="NVarChar(8) NOT NULL" CanBeNull="false" />
      <Column Name="GlobalPart" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="MtlAnalysisCode" Type="System.String" DbType="NVarChar(8) NOT NULL" CanBeNull="false" />
      <Column Name="GlobalLock" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="ISSuppUnitsFactor" Type="System.Decimal" DbType="Decimal(18,8) NOT NULL" CanBeNull="false" />
      <Column Name="PDMObjID" Type="System.String" DbType="NVarChar(8) NOT NULL" CanBeNull="false" />
      <Column Name="ImageFileName" Type="System.String" DbType="NVarChar(256) NOT NULL" CanBeNull="false" />
      <Column Name="ISOrigCountry" Type="System.String" DbType="NVarChar(6) NOT NULL" CanBeNull="false" />
      <Column Name="SNPrefix" Type="System.String" DbType="NVarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="SNFormat" Type="System.String" DbType="NVarChar(80) NOT NULL" CanBeNull="false" />
      <Column Name="SNBaseDataType" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="Constrained" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="UPCCode1" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="UPCCode2" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="UPCCode3" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="EDICode" Type="System.String" DbType="NVarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="WebInStock" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="ConsolidatedPurchasing" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="PurchasingFactorDirection" Type="System.String" DbType="NVarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="SellingFactorDirection" Type="System.String" DbType="NVarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="RecDocReq" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="MDPV" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ShipDocReq" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="ReturnableContainer" Type="System.String" DbType="NVarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="NetVolume" Type="System.Decimal" DbType="Decimal(15,5) NOT NULL" CanBeNull="false" />
      <Column Name="QtyBearing" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="NAFTAOrigCountry" Type="System.String" DbType="NVarChar(6) NOT NULL" CanBeNull="false" />
      <Column Name="NAFTAProd" Type="System.String" DbType="NVarChar(8) NOT NULL" CanBeNull="false" />
      <Column Name="NAFTAPref" Type="System.String" DbType="NVarChar(8) NOT NULL" CanBeNull="false" />
      <Column Name="ExpLicType" Type="System.String" DbType="NVarChar(8) NOT NULL" CanBeNull="false" />
      <Column Name="ExpLicNumber" Type="System.String" DbType="NVarChar(25) NOT NULL" CanBeNull="false" />
      <Column Name="ECCNNumber" Type="System.String" DbType="NVarChar(25) NOT NULL" CanBeNull="false" />
      <Column Name="AESExp" Type="System.String" DbType="NVarChar(8) NOT NULL" CanBeNull="false" />
      <Column Name="HTS" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="UseHTSDesc" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="SchedBcode" Type="System.String" DbType="NVarChar(12) NOT NULL" CanBeNull="false" />
      <Column Name="HazItem" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="HazTechName" Type="System.String" DbType="NVarChar(40) NOT NULL" CanBeNull="false" />
      <Column Name="HazClass" Type="System.String" DbType="NVarChar(8) NOT NULL" CanBeNull="false" />
      <Column Name="HazSub" Type="System.String" DbType="NVarChar(8) NOT NULL" CanBeNull="false" />
      <Column Name="HazGvrnmtID" Type="System.String" DbType="NVarChar(8) NOT NULL" CanBeNull="false" />
      <Column Name="HazPackInstr" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="RevChargeMethod" Type="System.String" DbType="NVarChar(8) NOT NULL" CanBeNull="false" />
      <Column Name="RCUnderThreshold" Type="System.Decimal" DbType="Decimal(17,3) NOT NULL" CanBeNull="false" />
      <Column Name="RCOverThreshold" Type="System.Decimal" DbType="Decimal(17,3) NOT NULL" CanBeNull="false" />
      <Column Name="OwnershipStatus" Type="System.String" DbType="NVarChar(8) NOT NULL" CanBeNull="false" />
      <Column Name="UOMClassID" Type="System.String" DbType="NVarChar(12) NOT NULL" CanBeNull="false" />
      <Column Name="SNMask" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="SNMaskExample" Type="System.String" DbType="NVarChar(80) NOT NULL" CanBeNull="false" />
      <Column Name="SNMaskSuffix" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="SNMaskPrefix" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="SNLastUsedSeq" Type="System.String" DbType="NVarChar(40) NOT NULL" CanBeNull="false" />
      <Column Name="UseMaskSeq" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="NetWeightUOM" Type="System.String" DbType="NVarChar(6) NOT NULL" CanBeNull="false" />
      <Column Name="NetVolumeUOM" Type="System.String" DbType="NVarChar(6) NOT NULL" CanBeNull="false" />
      <Column Name="LotBatch" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="LotMfgBatch" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="LotMfgLot" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="LotHeat" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="LotFirmware" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="LotBeforeDt" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="LotMfgDt" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="LotCureDt" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="LotExpDt" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="LotPrefix" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="LotUseGlobalSeq" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="LotSeqID" Type="System.String" DbType="NVarChar(12) NOT NULL" CanBeNull="false" />
      <Column Name="LotNxtNum" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="LotDigits" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="LotLeadingZeros" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="LotAppendDate" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="BuyToOrder" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="DropShip" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="IsConfigured" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="ExtConfig" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="RefCategory" Type="System.String" DbType="NVarChar(8) NOT NULL" CanBeNull="false" />
      <Column Name="CSFCJ5" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="CSFLMW" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="GrossWeight" Type="System.Decimal" DbType="Decimal(15,5) NOT NULL" CanBeNull="false" />
      <Column Name="GrossWeightUOM" Type="System.String" DbType="NVarChar(6) NOT NULL" CanBeNull="false" />
      <Column Name="BasePartNum" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="FSAssetClassCode" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="FSSalesUnitPrice" Type="System.Decimal" DbType="Decimal(17,5) NOT NULL" CanBeNull="false" />
      <Column Name="FSPricePerCode" Type="System.String" DbType="NVarChar(2) NOT NULL" CanBeNull="false" />
      <Column Name="RcvInspectionReq" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="EstimateID" Type="System.String" DbType="NVarChar(256) NOT NULL" CanBeNull="false" />
      <Column Name="EstimateOrPlan" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="DiffPrc2PrchUOM" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="DupOnJobCrt" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="PricingFactor" Type="System.Decimal" DbType="Decimal(14,5) NOT NULL" CanBeNull="false" />
      <Column Name="PricingUOM" Type="System.String" DbType="NVarChar(6) NOT NULL" CanBeNull="false" />
      <Column Name="MobilePart" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="SysRevID" Type="System.Data.Linq.Binary" DbType="rowversion NOT NULL" CanBeNull="false" IsVersion="true" />
      <Column Name="SysRowID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="AGUseGoodMark" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="AGProductMark" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="Erp.Customer" Member="Customers">
    <Type Name="Customer">
      <Column Name="Company" Type="System.String" DbType="NVarChar(8) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="CustID" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="CustNum" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Address1" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Address2" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Address3" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="City" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="State" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Zip" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="Country" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ResaleID" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="SalesRepCode" Type="System.String" DbType="NVarChar(8) NOT NULL" CanBeNull="false" />
      <Column Name="TerritoryID" Type="System.String" DbType="NVarChar(8) NOT NULL" CanBeNull="false" />
      <Column Name="ShipToNum" Type="System.String" DbType="NVarChar(14) NOT NULL" CanBeNull="false" />
      <Column Name="TermsCode" Type="System.String" DbType="NVarChar(4) NOT NULL" CanBeNull="false" />
      <Column Name="ShipViaCode" Type="System.String" DbType="NVarChar(4) NOT NULL" CanBeNull="false" />
      <Column Name="PrintStatements" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="PrintLabels" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="PrintAck" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="FinCharges" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="CreditHold" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="GroupCode" Type="System.String" DbType="NVarChar(4) NOT NULL" CanBeNull="false" />
      <Column Name="DiscountPercent" Type="System.Decimal" DbType="Decimal(6,2) NOT NULL" CanBeNull="false" />
      <Column Name="PrimPCon" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PrimBCon" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PrimSCon" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Comment" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="EstDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="FaxNum" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="PhoneNum" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="TaxExempt" Type="System.String" DbType="NVarChar(3) NOT NULL" CanBeNull="false" />
      <Column Name="MarkUpID" Type="System.String" DbType="NVarChar(4) NOT NULL" CanBeNull="false" />
      <Column Name="BillDay" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="OneInvPerPS" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="DefaultFOB" Type="System.String" DbType="NVarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="CreditIncludeOrders" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="CreditReviewDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="CreditHoldDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="CreditHoldSource" Type="System.String" DbType="NVarChar(8) NOT NULL" CanBeNull="false" />
      <Column Name="CreditClearUserID" Type="System.String" DbType="NVarChar(75) NOT NULL" CanBeNull="false" />
      <Column Name="CreditClearDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="CreditClearTime" Type="System.String" DbType="NVarChar(8) NOT NULL" CanBeNull="false" />
      <Column Name="EDICode" Type="System.String" DbType="NVarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="CurrencyCode" Type="System.String" DbType="NVarChar(4) NOT NULL" CanBeNull="false" />
      <Column Name="CountryNum" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="LangNameID" Type="System.String" DbType="NVarChar(8) NOT NULL" CanBeNull="false" />
      <Column Name="BorderCrossing" Type="System.String" DbType="NVarChar(4) NOT NULL" CanBeNull="false" />
      <Column Name="FormatStr" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="BTName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="BTAddress1" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="BTAddress2" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="BTAddress3" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="BTCity" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="BTState" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="BTZip" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="BTCountryNum" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="BTCountry" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="BTPhoneNum" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="BTFaxNum" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="BTFormatStr" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ParentCustNum" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TaxRegionCode" Type="System.String" DbType="NVarChar(4) NOT NULL" CanBeNull="false" />
      <Column Name="ICCust" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="ContBillDay" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="EMailAddress" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ShippingQualifier" Type="System.String" DbType="NVarChar(2) NOT NULL" CanBeNull="false" />
      <Column Name="AllocPriorityCode" Type="System.String" DbType="NVarChar(6) NOT NULL" CanBeNull="false" />
      <Column Name="ReservePriorityCode" Type="System.String" DbType="NVarChar(6) NOT NULL" CanBeNull="false" />
      <Column Name="LinkPortNum" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="WebCustomer" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="CustomerType" Type="System.String" DbType="NVarChar(3) NOT NULL" CanBeNull="false" />
      <Column Name="NoContact" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="TerritoryLock" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="CustURL" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="PendingTerritoryID" Type="System.String" DbType="NVarChar(8) NOT NULL" CanBeNull="false" />
      <Column Name="ExtID" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="ConsolidateSO" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="BillFrequency" Type="System.String" DbType="NVarChar(2) NOT NULL" CanBeNull="false" />
      <Column Name="CreditIncludePI" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="GlobalCust" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="ICTrader" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="TaxAuthorityCode" Type="System.String" DbType="NVarChar(8) NOT NULL" CanBeNull="false" />
      <Column Name="ExternalDeliveryNote" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="GlobalCredIncOrd" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="GlobalCredIncPI" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="GlobalCurrencyCode" Type="System.String" DbType="NVarChar(4) NOT NULL" CanBeNull="false" />
      <Column Name="ExternalID" Type="System.String" DbType="NVarChar(40) NOT NULL" CanBeNull="false" />
      <Column Name="GlobalCreditHold" Type="System.String" DbType="NVarChar(12) NOT NULL" CanBeNull="false" />
      <Column Name="GlobalLock" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="CheckDuplicatePO" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="CreditLimit" Type="System.Decimal" DbType="Decimal(15,0) NOT NULL" CanBeNull="false" />
      <Column Name="CustPILimit" Type="System.Decimal" DbType="Decimal(15,0) NOT NULL" CanBeNull="false" />
      <Column Name="GlobalCreditLimit" Type="System.Decimal" DbType="Decimal(15,0) NOT NULL" CanBeNull="false" />
      <Column Name="GlobalPILimit" Type="System.Decimal" DbType="Decimal(15,0) NOT NULL" CanBeNull="false" />
      <Column Name="DocGlobalCreditLimit" Type="System.Decimal" DbType="Decimal(15,0) NOT NULL" CanBeNull="false" />
      <Column Name="DocGlobalPILimit" Type="System.Decimal" DbType="Decimal(15,0) NOT NULL" CanBeNull="false" />
      <Column Name="RfqAttachAllow" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="DiscountQualifier" Type="System.String" DbType="NVarChar(3) NOT NULL" CanBeNull="false" />
      <Column Name="AllowAltBillTo" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="DemandDeliveryDays" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DemandDateType" Type="System.String" DbType="NVarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="DemandAddLeadTime" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DemandAddAction" Type="System.String" DbType="NVarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="DemandChangeLeadTime" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DemandChangeAction" Type="System.String" DbType="NVarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="DemandCancelLeadTime" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DemandCancelAction" Type="System.String" DbType="NVarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="DemandNewLineLeadTime" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DemandNewLineAction" Type="System.String" DbType="NVarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="DemandQtyChangeLeadTime" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DemandQtyChangeAction" Type="System.String" DbType="NVarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="DemandChangeDateLeadTime" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DemandChangeDateAction" Type="System.String" DbType="NVarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="TradingPartnerName" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="ResDelivery" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="SatDelivery" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="SatPickup" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Hazmat" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="DocOnly" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="RefNotes" Type="System.String" DbType="NVarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="ApplyChrg" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="ChrgAmount" Type="System.Decimal" DbType="Decimal(17,3) NOT NULL" CanBeNull="false" />
      <Column Name="COD" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="CODFreight" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="CODCheck" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="CODAmount" Type="System.Decimal" DbType="Decimal(17,3) NOT NULL" CanBeNull="false" />
      <Column Name="GroundType" Type="System.String" DbType="NVarChar(8) NOT NULL" CanBeNull="false" />
      <Column Name="NotifyFlag" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="NotifyEMail" Type="System.String" DbType="NVarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="DeclaredIns" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="DeclaredAmt" Type="System.Decimal" DbType="Decimal(17,3) NOT NULL" CanBeNull="false" />
      <Column Name="PeriodicityCode" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ServSignature" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="ServAlert" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="ServHomeDel" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="DeliveryType" Type="System.String" DbType="NVarChar(8) NOT NULL" CanBeNull="false" />
      <Column Name="ServDeliveryDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="ServPhone" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="ServInstruct" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="ServRelease" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="ServAuthNum" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ServRef1" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ServRef2" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ServRef3" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ServRef4" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ServRef5" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="EarlyBuffer" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="LateBuffer" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DemandUnitPriceDiff" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="DemandUnitPriceDiffAction" Type="System.String" DbType="NVarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="ExcFromVal" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="AddressVal" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="RebateVendorNum" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="RebateForm" Type="System.String" DbType="NVarChar(8) NOT NULL" CanBeNull="false" />
      <Column Name="CreditCardOrder" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="DemandCheckForPart" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="DemandCheckForPartAction" Type="System.String" DbType="NVarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="ChangedBy" Type="System.String" DbType="NVarChar(75) NOT NULL" CanBeNull="false" />
      <Column Name="ChangeDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="ChangeTime" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ChargeCode" Type="System.String" DbType="NVarChar(8) NOT NULL" CanBeNull="false" />
      <Column Name="IndividualPackIDs" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="IntrntlShip" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="CertOfOrigin" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="CommercialInvoice" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="ShipExprtDeclartn" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="LetterOfInstr" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="FFID" Type="System.String" DbType="NVarChar(8) NOT NULL" CanBeNull="false" />
      <Column Name="FFCompName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="FFAddress1" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="FFAddress2" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="FFAddress3" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="FFCity" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="FFState" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="FFZip" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="FFCountry" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="FFCountryNum" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="FFPhoneNum" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="NonStdPkg" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="DeliveryConf" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="AddlHdlgFlag" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="UPSQuantumView" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="UPSQVShipFromName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="UPSQVMemo" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="UPSQVEmailType" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="FFContact" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ETCAddrChg" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="TaxRoundRule" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TaxMethod" Type="System.String" DbType="NVarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="ValidPayer" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="ValidSoldTo" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="ValidShipTo" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="OverrideRlsClass" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="AcrossNatAcc" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="NAParentCreditIsUsed" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="NACreditIsShare" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="NACreditPreferenceList" Type="System.String" DbType="NVarChar(8) NOT NULL" CanBeNull="false" />
      <Column Name="NAParentCreditPrc" Type="System.Decimal" DbType="Decimal(7,2) NOT NULL" CanBeNull="false" />
      <Column Name="NACreditSharedPrc" Type="System.Decimal" DbType="Decimal(7,2) NOT NULL" CanBeNull="false" />
      <Column Name="AllowOTS" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="ThirdPLCust" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="ManagedVendID" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="ManagedVendNum" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="NARlsClassCode" Type="System.String" DbType="NVarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="DirectDebiting" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="ReminderCode" Type="System.String" DbType="NVarChar(8) NOT NULL" CanBeNull="false" />
      <Column Name="GlbNAParentCreditIsUsed" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="GlbNACreditIsShare" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="GlbNAParentCreditPrc" Type="System.Decimal" DbType="Decimal(7,2) NOT NULL" CanBeNull="false" />
      <Column Name="GlbNACreditSharedPrc" Type="System.Decimal" DbType="Decimal(7,2) NOT NULL" CanBeNull="false" />
      <Column Name="AllowShipTo3" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="OTSSaveAs" Type="System.String" DbType="NVarChar(2) NOT NULL" CanBeNull="false" />
      <Column Name="CustPartOpts" Type="System.String" DbType="NVarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="HasBank" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="PMUID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DemandCheckForRev" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="OrderHoldForReview" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="DemandCheckForRevAction" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ShipToTerrList" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="AcctRefNumber" Type="System.String" DbType="NVarChar(40) NOT NULL" CanBeNull="false" />
      <Column Name="ARInvoiceITCode" Type="System.String" DbType="NVarChar(12) NOT NULL" CanBeNull="false" />
      <Column Name="CreditMemoITCode" Type="System.String" DbType="NVarChar(12) NOT NULL" CanBeNull="false" />
      <Column Name="MiscCashRecITCode" Type="System.String" DbType="NVarChar(12) NOT NULL" CanBeNull="false" />
      <Column Name="LegalName" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="ARInvoiceAdjITCode" Type="System.String" DbType="NVarChar(12) NOT NULL" CanBeNull="false" />
      <Column Name="TaxRegReason" Type="System.String" DbType="NVarChar(12) NOT NULL" CanBeNull="false" />
      <Column Name="InvPerPackLine" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="OrgRegCode" Type="System.String" DbType="NVarChar(12) NOT NULL" CanBeNull="false" />
      <Column Name="DemandCloseRejSkd" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="OurBankCode" Type="System.String" DbType="NVarChar(5) NOT NULL" CanBeNull="false" />
      <Column Name="DemandCloseNoMatch" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="DmdCheckPartialShip" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="DmdCheckShipAction" Type="System.String" DbType="NVarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="DemandCheckCUMM" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="DemandCheckCUMMAction" Type="System.String" DbType="NVarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="DemandPricing" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="PriceTolerance" Type="System.Decimal" DbType="Decimal(17,5) NOT NULL" CanBeNull="false" />
      <Column Name="PreferredBank" Type="System.String" DbType="NVarChar(5) NOT NULL" CanBeNull="false" />
      <Column Name="CheckDateCapPromise" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="CheckConfirmCapPromise" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="CheckUpdateCapPromise" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="DemandCapPromiseDate" Type="System.String" DbType="NVarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="DemandCapPromiseAction" Type="System.String" DbType="NVarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="DemandCapPromiseUpdate" Type="System.String" DbType="NVarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="PeriodicBilling" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="DueDateCriteria" Type="System.String" DbType="NVarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="PBTerms" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ERSOrder" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="DemandSplitSched" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="OTSmartString" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="DeferredRev" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="RACode" Type="System.String" DbType="NVarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="DemandCheckConfig" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="DemandCheckCfgAction" Type="System.String" DbType="NVarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="AllowAsAltRemitTo" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="FederalID" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="WIApplication" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="WICustomer" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="WIShippingCosts" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="LOQBookPCFinishing" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="LOQBookPCPaper" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="LOQBookPCPress" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="LOQBookPCPlates" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Variations" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="OversPct" Type="System.Decimal" DbType="Decimal(14,5) NOT NULL" CanBeNull="false" />
      <Column Name="UndersPct" Type="System.Decimal" DbType="Decimal(14,5) NOT NULL" CanBeNull="false" />
      <Column Name="DefaultLOQstyle" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="DefaultOrderAcknowledgement" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="DefaultPackSlip" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="DefaultOversPricing" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="LOQPrepressStyle" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="CSR" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="LOQBookCaFinishing" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="LOQBookCapaper" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="LOQBookCaPress" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="LOQBookCatPlates" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="LOQVariations" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="DefaultInvoicestyle" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="AEPLOQType" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="BusinessCust" Type="System.String" DbType="NVarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="SysRevID" Type="System.Data.Linq.Binary" DbType="rowversion NOT NULL" CanBeNull="false" IsVersion="true" />
      <Column Name="SysRowID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="THBranchID" Type="System.String" DbType="NVarChar(8) NOT NULL" CanBeNull="false" />
      <Column Name="CustPricingSchema" Type="System.String" DbType="NVarChar(256) NOT NULL" CanBeNull="false" />
      <Column Name="ParamCode" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="AGAFIPResponsibilityCode" Type="System.String" DbType="NVarChar(4) NOT NULL" CanBeNull="false" />
      <Column Name="AGBillToProvinceCode" Type="System.String" DbType="NVarChar(4) NOT NULL" CanBeNull="false" />
      <Column Name="AGGrossIncomeTaxID" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="AGIDDocTypeCode" Type="System.String" DbType="NVarChar(4) NOT NULL" CanBeNull="false" />
      <Column Name="AGIDDocumentNumber" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="AGProvinceCode" Type="System.String" DbType="NVarChar(4) NOT NULL" CanBeNull="false" />
      <Column Name="AGUseGoodDefaultMark" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>